resize_shape: [256, 256]
targets: ["Fire_Images"]
model_file_paths:
  ["fire_cnn_classifier_params.h5", "fire_cnn_classifier_layers.json"]
base_model_url: "https://github.com/sammygrey/Fire-Detection-API-Project/releases/tag/v1.0.0"
model_sha256: "23d630e9605981c3a25adb00f73df3d83d842e0d"
